### PR TITLE
fix: typespec with optional params

### LINKED ISSUE #23: Dialyzer issues on Vault due to default params
```
lib/myapp/vault_config_provider.ex:15:unknown_function
Function Vault.auth/1 does not exist.
________________________________________________________________________________
lib/myapp/vault_config_provider.ex:15:unknown_function
Function Vault.new/1 does not exist.
________________________________________________________________________________
lib/myapp/vault_config_provider.ex:28:unknown_function
Function Vault.read/3 does not exist.
```

It seems that `Vault.read`, `Vault.new` and `Vault.auth` are failing because they have default inputs so they are arity of `2` but when I call them, I am not passing the second parameter so dialyzer things the function needs to be arity of `1`

Or something else ... since `Vault.new` is definitely arity of 1 so I am not sure.

here is the usage

```elixir
{:ok, vault} =
      Vault.new(
        engine: Vault.Engine.KVV2,
        http: Vault.HTTP.Tesla,
        json: Jason,
        host: System.fetch_env!("VAULT_ADDR"),
        auth: Vault.Auth.Kubernetes,
        credentials: %{
          role: System.fetch_env!("VAULT_K8S_ROLE"),
          jwt: File.read!(System.fetch_env!("VAULT_JWT_TOKEN_PATH"))
        }
      )
      |> Vault.auth()

    {:ok, vault_secrets} = Vault.read(vault, System.fetch_env!("VAULT_ENV_PATH"), [])
```

### PR DESCRIPTION
**Pull request by yordis**
fixes #23

### CODE REVIEW

**Comment by yordis** [comment]
@matthewoden share some love over here once you got some time 🙏🏻

**Comment by matthewoden** [comment]
@yordis Ugh, sorry for missing this! It got lost amongst my work github notifications. I'll try to find time to review this tonight, and try to publish a release if everything looks good.

**Comment by yordis** [comment]
@matthewoden, any updates?

**Comment by matthewoden** [comment]
Working on this tonight -- I haven't written elixir in a while (this library probably needs a new maintainer), VSCode literally throws up with my outdated elixir 1.9 install, and travis-ci.org shut down. I'll need to find a new build server.

Gonna get up to speed and _try_ to get this all published tonight. Probably going to put out a call for maintainers soon after that.

**Comment by matthewoden** [comment]
@yordis published.

**Pull request merged**
